version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
       POSTGRES_PASSWORD: root
       POSTGRES_USER: root
       POSTGRES_DB: user_service
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data

volumes: 
   db:
     driver: local
